//! Convert trajectory.jsonl into a standalone deterministic Python replay script.
//!
//! Usage: `eyetest codify <trajectory.jsonl> [--output replay.py] [--steps 1,2,3] [--delay 0.5]`

use std::io::BufRead;
use std::path::Path;

use serde::Deserialize;

use crate::error::AppError;

/// A trajectory entry as read back from the JSONL file.
#[derive(Debug, Deserialize)]
pub struct TrajectoryRecord {
    pub step: usize,
    pub timestamp: String,
    pub action_code: String,
    #[serde(default)]
    pub thought: Option<String>,
    #[serde(default)]
    pub screenshot_path: Option<String>,
    pub result: String,
}

/// Load trajectory entries from a JSONL file.
pub fn load_trajectory(path: &Path) -> Result<Vec<TrajectoryRecord>, AppError> {
    let file = std::fs::File::open(path)
        .map_err(|e| AppError::Config(format!("Cannot open trajectory file '{}': {e}", path.display())))?;

    let reader = std::io::BufReader::new(file);
    let mut entries = Vec::new();

    for (line_num, line) in reader.lines().enumerate() {
        let line = line.map_err(|e| AppError::Infra(format!("Error reading line {}: {e}", line_num + 1)))?;
        let line = line.trim().to_string();
        if line.is_empty() {
            continue;
        }
        let entry: TrajectoryRecord = serde_json::from_str(&line)
            .map_err(|e| AppError::Config(format!("Invalid JSON at line {}: {e}", line_num + 1)))?;
        entries.push(entry);
    }

    Ok(entries)
}

/// Generate a deterministic Python replay script from trajectory entries.
///
/// - `entries`: all trajectory entries
/// - `steps`: optional filter — only include these step numbers (1-indexed)
/// - `delay`: seconds to wait between steps
/// - `with_screenshots`: if true, add screenshot comparison assertions
/// - `threshold`: SSIM threshold for screenshot comparison (0.0-1.0)
pub fn generate_replay_script(
    entries: &[TrajectoryRecord],
    steps: Option<&[usize]>,
    delay: f64,
    with_screenshots: bool,
    threshold: f64,
) -> (String, usize) {
    let mut script = String::new();

    // Header
    script.push_str("#!/usr/bin/env python3\n");
    script.push_str("\"\"\"Deterministic replay script generated by eyetest codify.\"\"\"\n\n");
    script.push_str("import time\n");
    script.push_str("import pyautogui\n");
    if with_screenshots {
        script.push_str("import subprocess\n");
    }
    script.push_str("\n");
    script.push_str("# Safety settings\n");
    script.push_str("pyautogui.FAILSAFE = False\n");
    script.push_str("pyautogui.PAUSE = 0.1\n");
    script.push_str("\n");

    // Filter entries
    let filtered: Vec<&TrajectoryRecord> = entries
        .iter()
        .filter(|e| {
            if let Some(step_filter) = steps {
                step_filter.contains(&e.step)
            } else {
                // By default, include only successful action steps
                e.result == "success" || e.result == "done"
            }
        })
        .filter(|e| !e.action_code.trim().is_empty())
        .collect();

    // Generate step functions
    for entry in &filtered {
        let fn_name = format!("step_{:03}", entry.step);
        let mut docstring = entry
            .thought
            .as_deref()
            .unwrap_or("Execute action")
            .replace('\\', "\\\\")
            .replace("\"\"\"", "'''")
            .to_string();
        // Prevent trailing " from merging with closing """ to form """"
        // Strip trailing quotes and append a space to separate from closing """
        if docstring.ends_with('"') {
            let trimmed = docstring.trim_end_matches('"');
            let quote_count = docstring.len() - trimmed.len();
            docstring = format!("{}{} ", trimmed, "\"".repeat(quote_count));
        }

        script.push_str(&format!("def {fn_name}():\n"));
        script.push_str(&format!("    \"\"\"{docstring}\"\"\"\n"));

        // Indent each line of action code
        for line in entry.action_code.lines() {
            if line.trim().is_empty() {
                script.push_str("\n");
            } else {
                script.push_str(&format!("    {line}\n"));
            }
        }
        script.push('\n');

        // Optional screenshot assertion
        if with_screenshots {
            if let Some(screenshot) = &entry.screenshot_path {
                script.push_str(&format!(
                    "    # Screenshot assertion (threshold: {threshold})\n"
                ));
                script.push_str(
                    "    time.sleep(0.5)  # Wait for UI to settle\n"
                );
                script.push_str(
                    "    subprocess.run(['scrot', '/tmp/_replay_actual.png'], check=True)\n"
                );
                script.push_str(
                    "    subprocess.run(['python3', '/usr/local/bin/screenshot-compare',\n"
                );
                let screenshot_escaped = screenshot.replace('\\', "\\\\").replace('\'', "\\'");
                script.push_str(&format!(
                    "        '--expected', '{screenshot_escaped}', '--actual', '/tmp/_replay_actual.png', '--threshold', '{threshold}'], check=True)\n"
                ));
            }
        }

        script.push('\n');
    }

    // Main execution
    script.push_str("def main():\n");
    script.push_str("    \"\"\"Run all replay steps.\"\"\"\n");
    script.push_str("    print('REPLAY_START')\n");
    for (i, entry) in filtered.iter().enumerate() {
        let fn_name = format!("step_{:03}", entry.step);
        if i > 0 {
            script.push_str(&format!("    time.sleep({delay})\n"));
        }
        script.push_str(&format!(
            "    print('Step {}: {}...')\n",
            entry.step,
            entry
                .thought
                .as_deref()
                .unwrap_or("action")
                .chars()
                .filter(|c| *c != '\n' && *c != '\r')
                .take(50)
                .collect::<String>()
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
        ));
        script.push_str(&format!("    {fn_name}()\n"));
    }
    script.push_str("    print('REPLAY_COMPLETE')\n");
    script.push('\n');

    script.push_str("\nif __name__ == '__main__':\n");
    script.push_str("    main()\n");

    let count = filtered.len();
    (script, count)
}

/// Parse a comma-separated list of step numbers.
pub fn parse_steps(steps_str: &str) -> Result<Vec<usize>, AppError> {
    steps_str
        .split(',')
        .map(|s| {
            s.trim()
                .parse::<usize>()
                .map_err(|e| AppError::Config(format!("Invalid step number '{s}': {e}")))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entries() -> Vec<TrajectoryRecord> {
        vec![
            TrajectoryRecord {
                step: 1,
                timestamp: "2026-01-01T00:00:00Z".into(),
                action_code: "pyautogui.click(100, 200)".into(),
                thought: Some("Click the button".into()),
                screenshot_path: Some("step_001.png".into()),
                result: "success".into(),
            },
            TrajectoryRecord {
                step: 2,
                timestamp: "2026-01-01T00:00:01Z".into(),
                action_code: "pyautogui.typewrite('hello')".into(),
                thought: Some("Type hello".into()),
                screenshot_path: Some("step_002.png".into()),
                result: "success".into(),
            },
            TrajectoryRecord {
                step: 3,
                timestamp: "2026-01-01T00:00:02Z".into(),
                action_code: "".into(),
                thought: Some("Task complete".into()),
                screenshot_path: None,
                result: "done".into(),
            },
        ]
    }

    #[test]
    fn test_generate_replay_basic() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, None, 0.5, false, 0.95);
        assert!(script.contains("#!/usr/bin/env python3"));
        assert!(script.contains("def step_001():"));
        assert!(script.contains("def step_002():"));
        assert!(script.contains("pyautogui.click(100, 200)"));
        assert!(script.contains("pyautogui.typewrite('hello')"));
        assert!(script.contains("REPLAY_COMPLETE"));
        assert!(script.contains("time.sleep(0.5)"));
    }

    #[test]
    fn test_generate_replay_filtered_steps() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, Some(&[2]), 1.0, false, 0.95);
        assert!(!script.contains("def step_001():"));
        assert!(script.contains("def step_002():"));
    }

    #[test]
    fn test_generate_replay_with_screenshots() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, None, 0.5, true, 0.95);
        assert!(script.contains("import subprocess"));
        assert!(script.contains("screenshot-compare"));
    }

    #[test]
    fn test_parse_steps() {
        let steps = parse_steps("1,3,5").unwrap();
        assert_eq!(steps, vec![1, 3, 5]);
    }

    #[test]
    fn test_parse_steps_with_spaces() {
        let steps = parse_steps("1, 2, 3").unwrap();
        assert_eq!(steps, vec![1, 2, 3]);
    }

    #[test]
    fn test_parse_steps_invalid() {
        assert!(parse_steps("1,abc,3").is_err());
    }

    #[test]
    fn test_empty_action_code_filtered() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, None, 0.5, false, 0.95);
        // Step 3 has empty action_code, should be filtered out
        assert!(!script.contains("def step_003():"));
    }

    #[test]
    fn test_load_trajectory_from_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("trajectory.jsonl");
        std::fs::write(&path, "{\"step\":1,\"timestamp\":\"2026-01-01T00:00:00Z\",\"action_code\":\"pyautogui.click(100,200)\",\"result\":\"success\"}\n{\"step\":2,\"timestamp\":\"2026-01-01T00:00:01Z\",\"action_code\":\"pyautogui.press('enter')\",\"result\":\"done\"}\n").unwrap();

        let entries = load_trajectory(&path).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].step, 1);
        assert_eq!(entries[1].step, 2);
    }
}
