//! Convert trajectory.jsonl into a standalone deterministic Python replay script.
//!
//! Usage: `desktest codify <trajectory.jsonl> [--output desktest_replay.py] [--steps 1,2,3] [--delay 0.5]`

use std::io::BufRead;
use std::path::Path;

use base64::Engine;
use serde::Deserialize;

use crate::error::AppError;

/// A trajectory entry as read back from the JSONL file.
#[derive(Debug, Deserialize)]
pub struct TrajectoryRecord {
    pub step: usize,
    pub timestamp: String,
    pub action_code: String,
    #[serde(default)]
    pub thought: Option<String>,
    #[serde(default)]
    pub screenshot_path: Option<String>,
    pub result: String,
    #[serde(default)]
    pub bash_output: Option<String>,
    #[serde(default)]
    pub error_feedback: Option<String>,
    #[serde(default)]
    pub action_type: Option<String>,
}

/// Load trajectory entries from a JSONL file.
pub fn load_trajectory(path: &Path) -> Result<Vec<TrajectoryRecord>, AppError> {
    let file = std::fs::File::open(path).map_err(|e| {
        AppError::Config(format!(
            "Cannot open trajectory file '{}': {e}",
            path.display()
        ))
    })?;

    let reader = std::io::BufReader::new(file);
    let mut entries = Vec::new();

    for (line_num, line) in reader.lines().enumerate() {
        let line =
            line.map_err(|e| AppError::Infra(format!("Error reading line {}: {e}", line_num + 1)))?;
        let line = line.trim().to_string();
        if line.is_empty() {
            continue;
        }
        let entry: TrajectoryRecord = serde_json::from_str(&line)
            .map_err(|e| AppError::Config(format!("Invalid JSON at line {}: {e}", line_num + 1)))?;
        entries.push(entry);
    }

    Ok(entries)
}

/// Generate a deterministic Python replay script from trajectory entries.
///
/// - `entries`: all trajectory entries
/// - `steps`: optional filter — only include these step numbers (1-indexed)
/// - `delay`: seconds to wait between steps
/// - `with_screenshots`: if true, add screenshot comparison assertions
/// - `threshold`: pixel similarity threshold for screenshot comparison (MAE-based, 0.0-1.0)
/// * `screenshots_dir_name`: when `with_screenshots` is true, the directory name
///   under `/home/tester/` where expected screenshots will be found in the container.
///   Defaults to the current directory if None.
pub fn generate_replay_script(
    entries: &[TrajectoryRecord],
    steps: Option<&[usize]>,
    delay: f64,
    with_screenshots: bool,
    threshold: f64,
    screenshots_dir_name: Option<&str>,
) -> (String, usize) {
    let mut script = String::new();

    // Header
    script.push_str("#!/usr/bin/env python3\n");
    script.push_str("\"\"\"Deterministic replay script generated by desktest codify.\"\"\"\n\n");
    script.push_str("import time\n");
    script.push_str("import pyautogui\n");
    script.push_str("import subprocess\n");
    script.push('\n');
    script.push_str("# Safety settings\n");
    script.push_str("pyautogui.FAILSAFE = False\n");
    script.push_str("pyautogui.PAUSE = 0.1\n");
    script.push('\n');

    // Filter entries
    let filter_set: Option<std::collections::HashSet<usize>> =
        steps.map(|s| s.iter().copied().collect());
    let filtered: Vec<&TrajectoryRecord> = entries
        .iter()
        .filter(|e| {
            if let Some(ref set) = filter_set {
                set.contains(&e.step)
            } else {
                // By default, include only successful action steps
                e.result == "success" || e.result == "done"
            }
        })
        .filter(|e| {
            let keep = !e.action_code.trim().is_empty();
            if !keep {
                if let Some(ref set) = filter_set {
                    if set.contains(&e.step) {
                        eprintln!(
                            "Warning: step {} has empty action_code and will be skipped",
                            e.step
                        );
                    }
                }
            }
            keep
        })
        .collect();

    // Deduplicate by step number (keep last entry for each step)
    let mut seen = std::collections::HashMap::new();
    for entry in &filtered {
        seen.insert(entry.step, *entry);
    }
    let mut filtered: Vec<&TrajectoryRecord> = seen.into_values().collect();
    filtered.sort_by_key(|e| e.step);

    // Generate step functions
    for entry in &filtered {
        let fn_name = format!("step_{:03}", entry.step);
        let mut docstring = entry
            .thought
            .as_deref()
            .unwrap_or("Execute action")
            .replace('\\', "\\\\")
            .replace("\"\"\"", "'''")
            .replace('\n', " ")
            .replace('\r', "")
            .to_string();
        // Prevent trailing " from merging with closing """ to form """"
        // Strip trailing quotes and append a space to separate from closing """
        if docstring.ends_with('"') {
            let trimmed = docstring.trim_end_matches('"');
            let quote_count = docstring.len() - trimmed.len();
            docstring = format!("{}{} ", trimmed, "\"".repeat(quote_count));
        }

        script.push_str(&format!("def {fn_name}():\n"));
        script.push_str(&format!("    \"\"\"{docstring}\"\"\"\n"));

        // Screenshot assertion BEFORE action (trajectory screenshots are pre-action observations)
        if with_screenshots {
            if let Some(screenshot) = &entry.screenshot_path {
                script.push_str(&format!(
                    "    # Verify pre-action screen state (threshold: {threshold})\n"
                ));
                script.push_str("    time.sleep(0.5)  # Wait for UI to settle\n");
                script.push_str(
                    "    subprocess.run(['scrot', '/tmp/_replay_actual.png'], check=True)\n",
                );
                script.push_str(
                    "    subprocess.run(['python3', '/usr/local/bin/screenshot-compare',\n",
                );
                // Build container path: /home/tester/<dir_name>/<filename>
                let container_screenshot = if let Some(dir_name) = screenshots_dir_name {
                    format!("/home/tester/{dir_name}/{screenshot}")
                } else {
                    format!("/home/tester/{screenshot}")
                };
                let screenshot_escaped = container_screenshot
                    .replace('\\', "\\\\")
                    .replace('\'', "\\'");
                script.push_str(&format!(
                    "        '--expected', '{screenshot_escaped}', '--actual', '/tmp/_replay_actual.png', '--threshold', '{threshold}'], check=True)\n"
                ));
            }
        }

        // Action code (strip trailing blank lines)
        // NOTE: action code may contain return/sys.exit() which would short-circuit the step
        for line in entry.action_code.trim_end_matches('\n').lines() {
            if line.trim().is_empty() {
                script.push('\n');
            } else {
                script.push_str(&format!("    {line}\n"));
            }
        }

        script.push('\n');
    }

    // Main execution
    script.push_str("def main():\n");
    script.push_str("    \"\"\"Run all replay steps.\"\"\"\n");
    script.push_str("    print('REPLAY_START')\n");
    for (i, entry) in filtered.iter().enumerate() {
        let fn_name = format!("step_{:03}", entry.step);
        if i > 0 {
            script.push_str(&format!("    time.sleep({delay})\n"));
        }
        script.push_str(&format!(
            "    print('Step {}: {}...')\n",
            entry.step,
            entry
                .thought
                .as_deref()
                .unwrap_or("action")
                .chars()
                .filter(|c| *c != '\n' && *c != '\r')
                .take(50)
                .collect::<String>()
                .replace('\\', "\\\\")
                .replace('\'', "\\'")
        ));
        script.push_str(&format!("    {fn_name}()\n"));
        script.push_str(&format!(
            "    subprocess.run(['scrot', '/tmp/replay_step_{:03}.png'], check=False)\n",
            entry.step
        ));
        // Emit structured marker for trajectory reconstruction (capped at 200 chars
        // to keep generated scripts readable; full thought lives in the original trajectory)
        let thought_escaped = entry
            .thought
            .as_deref()
            .unwrap_or("action")
            .chars()
            .filter(|c| *c != '\n' && *c != '\r')
            .take(200)
            .collect::<String>()
            .replace('\\', "\\\\")
            .replace('\'', "\\'");
        script.push_str(&format!(
            "    print('REPLAY_STEP_DONE:{}:{}')\n",
            entry.step, thought_escaped
        ));
        // Emit base64-encoded action code for trajectory reconstruction
        let action_b64 = base64::engine::general_purpose::STANDARD.encode(&entry.action_code);
        script.push_str(&format!(
            "    print('REPLAY_ACTION:{}:{}')\n",
            entry.step, action_b64
        ));
    }
    script.push_str("    print('REPLAY_COMPLETE')\n");
    script.push('\n');

    script.push_str("\nif __name__ == '__main__':\n");
    script.push_str("    main()\n");

    let count = filtered.len();
    (script, count)
}

/// Parse a comma-separated list of step numbers and ranges (e.g. "1,3,5-8").
pub fn parse_steps(steps_str: &str) -> Result<Vec<usize>, AppError> {
    let mut result = Vec::new();
    for part in steps_str.split(',') {
        let part = part.trim();
        if let Some((start_str, end_str)) = part.split_once('-') {
            if start_str.trim().is_empty() || end_str.trim().is_empty() {
                return Err(AppError::Config(format!(
                    "Invalid step range '{part}': expected format N-M"
                )));
            }
            let start: usize = start_str
                .trim()
                .parse()
                .map_err(|e| AppError::Config(format!("Invalid step number '{start_str}': {e}")))?;
            let end: usize = end_str
                .trim()
                .parse()
                .map_err(|e| AppError::Config(format!("Invalid step number '{end_str}': {e}")))?;
            if start > end {
                return Err(AppError::Config(format!(
                    "Invalid step range '{part}': start ({start}) is greater than end ({end})"
                )));
            }
            result.extend(start..=end);
        } else {
            let n: usize = part
                .parse()
                .map_err(|e| AppError::Config(format!("Invalid step number '{part}': {e}")))?;
            result.push(n);
        }
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_entries() -> Vec<TrajectoryRecord> {
        vec![
            TrajectoryRecord {
                step: 1,
                timestamp: "2026-01-01T00:00:00Z".into(),
                action_code: "pyautogui.click(100, 200)".into(),
                thought: Some("Click the button".into()),
                screenshot_path: Some("step_001.png".into()),
                result: "success".into(),
                bash_output: None,
                error_feedback: None,
                action_type: None,
            },
            TrajectoryRecord {
                step: 2,
                timestamp: "2026-01-01T00:00:01Z".into(),
                action_code: "pyautogui.typewrite('hello')".into(),
                thought: Some("Type hello".into()),
                screenshot_path: Some("step_002.png".into()),
                result: "success".into(),
                bash_output: None,
                error_feedback: None,
                action_type: None,
            },
            TrajectoryRecord {
                step: 3,
                timestamp: "2026-01-01T00:00:02Z".into(),
                action_code: "".into(),
                thought: Some("Task complete".into()),
                screenshot_path: None,
                result: "done".into(),
                bash_output: None,
                error_feedback: None,
                action_type: None,
            },
        ]
    }

    #[test]
    fn test_generate_replay_basic() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, None, 0.5, false, 0.95, None);
        assert!(script.contains("#!/usr/bin/env python3"));
        assert!(script.contains("def step_001():"));
        assert!(script.contains("def step_002():"));
        assert!(script.contains("pyautogui.click(100, 200)"));
        assert!(script.contains("pyautogui.typewrite('hello')"));
        assert!(script.contains("REPLAY_COMPLETE"));
        assert!(script.contains("time.sleep(0.5)"));
    }

    #[test]
    fn test_generate_replay_filtered_steps() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, Some(&[2]), 1.0, false, 0.95, None);
        assert!(!script.contains("def step_001():"));
        assert!(script.contains("def step_002():"));
    }

    #[test]
    fn test_generate_replay_with_screenshots() {
        let entries = sample_entries();
        let (script, _count) =
            generate_replay_script(&entries, None, 0.5, true, 0.95, Some("artifacts"));
        assert!(script.contains("import subprocess"));
        assert!(script.contains("screenshot-compare"));
    }

    #[test]
    fn test_parse_steps() {
        let steps = parse_steps("1,3,5").unwrap();
        assert_eq!(steps, vec![1, 3, 5]);
    }

    #[test]
    fn test_parse_steps_with_spaces() {
        let steps = parse_steps("1, 2, 3").unwrap();
        assert_eq!(steps, vec![1, 2, 3]);
    }

    #[test]
    fn test_parse_steps_with_range() {
        let steps = parse_steps("3-7").unwrap();
        assert_eq!(steps, vec![3, 4, 5, 6, 7]);
    }

    #[test]
    fn test_parse_steps_mixed_ranges_and_singles() {
        let steps = parse_steps("1,3,5-8").unwrap();
        assert_eq!(steps, vec![1, 3, 5, 6, 7, 8]);
    }

    #[test]
    fn test_parse_steps_single_element_range() {
        let steps = parse_steps("5-5").unwrap();
        assert_eq!(steps, vec![5]);
    }

    #[test]
    fn test_parse_steps_invalid_range() {
        assert!(parse_steps("7-3").is_err());
    }

    #[test]
    fn test_parse_steps_invalid() {
        assert!(parse_steps("1,abc,3").is_err());
    }

    #[test]
    fn test_parse_steps_leading_dash() {
        let err = parse_steps("-5").unwrap_err();
        assert!(err.to_string().contains("expected format N-M"));
    }

    #[test]
    fn test_parse_steps_trailing_dash() {
        let err = parse_steps("5-").unwrap_err();
        assert!(err.to_string().contains("expected format N-M"));
    }

    #[test]
    fn test_empty_action_code_filtered() {
        let entries = sample_entries();
        let (script, _count) = generate_replay_script(&entries, None, 0.5, false, 0.95, None);
        // Step 3 has empty action_code, should be filtered out
        assert!(!script.contains("def step_003():"));
    }

    #[test]
    fn test_load_trajectory_from_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("trajectory.jsonl");
        std::fs::write(&path, "{\"step\":1,\"timestamp\":\"2026-01-01T00:00:00Z\",\"action_code\":\"pyautogui.click(100,200)\",\"result\":\"success\"}\n{\"step\":2,\"timestamp\":\"2026-01-01T00:00:01Z\",\"action_code\":\"pyautogui.press('enter')\",\"result\":\"done\"}\n").unwrap();

        let entries = load_trajectory(&path).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].step, 1);
        assert_eq!(entries[1].step, 2);
    }
}
