use serde_json::{Value, json};

/// Generate a JSON Schema for the task definition format.
///
/// This is hand-written rather than derived because:
/// 1. schemars adds a heavy dependency
/// 2. We need to match serde's `#[serde(tag = "type")]` discriminator pattern exactly
/// 3. We want human-friendly descriptions inline
pub fn generate_task_schema() -> Value {
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://desktest.dev/schemas/task-v1.0.json",
        "title": "Desktest Task Definition",
        "description": "Schema for desktest task JSON files (schema_version 1.0)",
        "type": "object",
        "required": ["schema_version", "id", "instruction", "app"],
        "additionalProperties": false,
        "properties": {
            "schema_version": {
                "type": "string",
                "const": "1.0",
                "description": "Schema version. Must be \"1.0\"."
            },
            "id": {
                "type": "string",
                "minLength": 1,
                "description": "Unique identifier for this task."
            },
            "instruction": {
                "type": "string",
                "minLength": 1,
                "description": "Natural language instruction for the agent — what it should do."
            },
            "completion_condition": {
                "type": "string",
                "description": "Optional description of when the agent should consider the task done."
            },
            "app": { "$ref": "#/$defs/AppConfig" },
            "config": {
                "type": "array",
                "items": { "$ref": "#/$defs/SetupStep" },
                "default": [],
                "description": "Setup steps to execute before the agent loop."
            },
            "evaluator": { "$ref": "#/$defs/EvaluatorConfig" },
            "timeout": {
                "type": "integer",
                "minimum": 1,
                "default": 300,
                "description": "Overall test timeout in seconds."
            },
            "max_steps": {
                "type": "integer",
                "minimum": 1,
                "default": 15,
                "description": "Maximum steps for the agent loop."
            },
            "a11y_timeout_secs": {
                "type": "integer",
                "minimum": 1,
                "description": "Accessibility tree extraction timeout in seconds. Skips adaptive probe if set."
            },
            "max_a11y_nodes": {
                "type": "integer",
                "minimum": 1,
                "default": 10000,
                "description": "Maximum number of accessibility tree nodes to extract."
            },
            "secrets": {
                "type": "object",
                "additionalProperties": { "$ref": "#/$defs/SecretDef" },
                "description": "Named secrets sourced from environment variables. Keys are placeholder names for {{key}} substitution."
            },
            "metadata": {
                "description": "Arbitrary metadata (tags, author, description, etc.)."
            },
            "replay_script": {
                "type": "string",
                "description": "Path to a codified Python replay script (generated by `desktest codify`)."
            },
            "replay_screenshots_dir": {
                "type": "string",
                "description": "Directory containing expected screenshots for replay visual assertions."
            },
            "early_exit": { "$ref": "#/$defs/EarlyExitConfig" }
        },
        "$defs": {
            "SecretDef": secret_def_schema(),
            "AppConfig": app_config_schema(),
            "SetupStep": setup_step_schema(),
            "EvaluatorConfig": evaluator_config_schema(),
            "MetricConfig": metric_config_schema(),
            "EarlyExitConfig": early_exit_config_schema(),
            "EarlyExitCondition": early_exit_condition_schema()
        }
    })
}

fn secret_def_schema() -> Value {
    json!({
        "type": "object",
        "required": ["env"],
        "additionalProperties": false,
        "properties": {
            "env": {
                "type": "string",
                "description": "Environment variable name to read the secret value from."
            },
            "default": {
                "type": "string",
                "description": "Optional default value when the environment variable is not set."
            }
        }
    })
}

fn app_config_schema() -> Value {
    json!({
        "description": "Application deployment configuration. The 'type' field selects the deployment model.",
        "oneOf": [
            {
                "type": "object",
                "description": "Deploy an AppImage file into the container.",
                "required": ["type", "path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "appimage" },
                    "path": { "type": "string", "description": "Path to the AppImage file." },
                    "electron": { "type": "boolean", "default": false, "description": "Whether this is an Electron app." }
                }
            },
            {
                "type": "object",
                "description": "Deploy a folder-based app with a shell entrypoint.",
                "required": ["type", "dir", "entrypoint"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "folder" },
                    "dir": { "type": "string", "description": "Path to the app directory." },
                    "entrypoint": { "type": "string", "description": "Shell script to launch the app." },
                    "electron": { "type": "boolean", "default": false, "description": "Whether this is an Electron app." }
                }
            },
            {
                "type": "object",
                "description": "Use a pre-built custom Docker image.",
                "required": ["type", "image"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "docker_image" },
                    "image": { "type": "string", "description": "Docker image name (e.g., my-app:latest)." },
                    "digest": { "type": "string", "pattern": "^sha256:[a-f0-9]{64}$", "description": "Optional image digest for pinning." },
                    "entrypoint_cmd": { "type": "string", "description": "Custom entrypoint command." },
                    "needs_fuse": { "type": "boolean", "default": false, "description": "Grant CAP_SYS_ADMIN and /dev/fuse access." }
                }
            },
            {
                "type": "object",
                "description": "Attach to an existing running desktop (for `desktest attach` mode).",
                "required": ["type"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "vnc_attach" },
                    "note": { "type": "string", "description": "Optional note about the attach target." }
                }
            },
            {
                "type": "object",
                "description": "Run a macOS app inside a Tart VM.",
                "required": ["type", "base_image"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "macos_tart" },
                    "base_image": { "type": "string", "description": "Tart base image to clone (e.g., desktest-macos:latest)." },
                    "bundle_id": { "type": "string", "description": "macOS bundle identifier (e.g., com.apple.TextEdit)." },
                    "app_path": { "type": "string", "description": "Path to a .app bundle." },
                    "launch_cmd": { "type": "string", "description": "Arbitrary launch command (takes precedence)." },
                    "electron": { "type": "boolean", "default": false, "description": "Whether this is an Electron app." }
                },
                "anyOf": [
                    { "required": ["bundle_id"] },
                    { "required": ["app_path"] },
                    { "required": ["launch_cmd"] }
                ]
            },
            {
                "type": "object",
                "description": "Test a macOS app on the host desktop (no VM).",
                "required": ["type"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "macos_native" },
                    "bundle_id": { "type": "string", "description": "macOS bundle identifier." },
                    "app_path": { "type": "string", "description": "Path to a .app bundle on the host." }
                },
                "anyOf": [
                    { "required": ["bundle_id"] },
                    { "required": ["app_path"] }
                ]
            },
            {
                "type": "object",
                "description": "Run a Windows app inside a QEMU/KVM VM.",
                "required": ["type", "base_image"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "windows_vm" },
                    "base_image": { "type": "string", "description": "Path to QCOW2 golden image." },
                    "app_path": { "type": "string", "description": "App file to deploy into the VM." },
                    "launch_cmd": { "type": "string", "description": "PowerShell launch command." },
                    "installer_cmd": { "type": "string", "description": "Installer command to run after deployment." }
                },
                "anyOf": [
                    { "required": ["app_path"] },
                    { "required": ["launch_cmd"] }
                ]
            },
            {
                "type": "object",
                "description": "Test a Windows app on the host desktop (no VM).",
                "required": ["type"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "windows_native" },
                    "app_path": { "type": "string", "description": "Path to the application executable." },
                    "launch_cmd": { "type": "string", "description": "PowerShell/cmd launch command." }
                },
                "anyOf": [
                    { "required": ["app_path"] },
                    { "required": ["launch_cmd"] }
                ]
            }
        ]
    })
}

fn setup_step_schema() -> Value {
    json!({
        "description": "A setup step to execute before the agent loop.",
        "oneOf": [
            {
                "type": "object",
                "description": "Run a shell command inside the container.",
                "required": ["type", "command"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "execute" },
                    "command": { "type": "string", "minLength": 1 }
                }
            },
            {
                "type": "object",
                "description": "Copy a file or directory into the container.",
                "required": ["type", "src", "dest"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "copy" },
                    "src": { "type": "string", "minLength": 1, "description": "Source path on the host." },
                    "dest": { "type": "string", "minLength": 1, "description": "Destination path in the container." }
                }
            },
            {
                "type": "object",
                "description": "Open a file with xdg-open or a specified application.",
                "required": ["type", "target"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "open" },
                    "target": { "type": "string", "minLength": 1, "description": "File or URL to open." },
                    "app": { "type": "string", "description": "Application to open with (optional)." }
                }
            },
            {
                "type": "object",
                "description": "Wait for a specified number of seconds.",
                "required": ["type", "seconds"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "sleep" },
                    "seconds": { "type": "number", "exclusiveMinimum": 0 }
                }
            }
        ]
    })
}

fn evaluator_config_schema() -> Value {
    json!({
        "type": "object",
        "description": "Evaluation configuration for determining test pass/fail.",
        "required": ["mode"],
        "additionalProperties": false,
        "properties": {
            "mode": {
                "type": "string",
                "enum": ["llm", "programmatic", "hybrid"],
                "description": "llm = agent verdict only, programmatic = metrics only (no agent loop), hybrid = both required."
            },
            "metrics": {
                "type": "array",
                "items": { "$ref": "#/$defs/MetricConfig" },
                "description": "Programmatic metrics (used in programmatic and hybrid modes)."
            },
            "conjunction": {
                "type": "string",
                "enum": ["and", "or"],
                "default": "and",
                "description": "How to combine multiple metrics: 'and' (all must pass) or 'or' (any must pass)."
            },
            "eval_timeout_secs": {
                "type": "integer",
                "minimum": 1,
                "description": "Per-execution timeout in seconds for evaluator commands."
            }
        }
    })
}

fn metric_config_schema() -> Value {
    json!({
        "description": "A programmatic evaluation metric.",
        "oneOf": [
            {
                "type": "object",
                "description": "Compare a file from the container against an expected file.",
                "required": ["type", "actual_path", "expected_path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "file_compare" },
                    "actual_path": { "type": "string", "description": "Path to the file inside the container." },
                    "expected_path": { "type": "string", "description": "Path to the expected file on the host." },
                    "compare_mode": { "type": "string", "enum": ["exact", "normalized"], "default": "exact", "description": "Comparison mode." }
                }
            },
            {
                "type": "object",
                "description": "Semantically compare structured data files.",
                "required": ["type", "actual_path", "expected_path", "format"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "file_compare_semantic" },
                    "actual_path": { "type": "string" },
                    "expected_path": { "type": "string" },
                    "format": { "type": "string", "enum": ["json", "yaml", "xml", "csv"], "description": "File format for semantic parsing." }
                }
            },
            {
                "type": "object",
                "description": "Run a command and check stdout.",
                "required": ["type", "command", "expected"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "command_output" },
                    "command": { "type": "string", "description": "Command to run inside the container." },
                    "expected": { "type": "string", "description": "Expected output." },
                    "match_mode": { "type": "string", "enum": ["contains", "equals", "regex"], "default": "contains" }
                }
            },
            {
                "type": "object",
                "description": "Check if a file exists (or does not exist) in the container.",
                "required": ["type", "path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "file_exists" },
                    "path": { "type": "string", "description": "Path to check inside the container." },
                    "should_not_exist": { "type": "boolean", "default": false, "description": "If true, assert the file does NOT exist." }
                }
            },
            {
                "type": "object",
                "description": "Run a command and check its exit code.",
                "required": ["type", "command", "expected"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "exit_code" },
                    "command": { "type": "string", "description": "Command to run inside the container." },
                    "expected": { "type": "integer", "description": "Expected exit code." }
                }
            },
            {
                "type": "object",
                "description": "Run a Python replay script inside the container.",
                "required": ["type", "script_path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "script_replay" },
                    "script_path": { "type": "string", "description": "Path to the Python script on the host." },
                    "screenshots_dir": { "type": "string", "description": "Directory containing expected screenshots." }
                }
            }
        ]
    })
}

fn early_exit_config_schema() -> Value {
    json!({
        "type": "object",
        "description": "Early exit configuration — exit the agent loop early when a condition is met.",
        "required": ["condition"],
        "additionalProperties": false,
        "properties": {
            "condition": { "$ref": "#/$defs/EarlyExitCondition" },
            "check_every": {
                "type": "integer",
                "minimum": 1,
                "default": 1,
                "description": "Check every N steps."
            },
            "message": {
                "type": "string",
                "description": "Human-readable message for the early exit reason."
            }
        }
    })
}

fn early_exit_condition_schema() -> Value {
    json!({
        "description": "Condition for early exit — programmatic check or LLM judgment.",
        "oneOf": [
            {
                "type": "object",
                "required": ["type", "actual_path", "expected_path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "file_compare" },
                    "actual_path": { "type": "string" },
                    "expected_path": { "type": "string" },
                    "compare_mode": { "type": "string", "enum": ["exact", "normalized"], "default": "exact" }
                }
            },
            {
                "type": "object",
                "required": ["type", "command", "expected"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "command_output" },
                    "command": { "type": "string" },
                    "expected": { "type": "string" },
                    "match_mode": { "type": "string", "enum": ["contains", "equals", "regex"], "default": "contains" }
                }
            },
            {
                "type": "object",
                "required": ["type", "path"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "file_exists" },
                    "path": { "type": "string" },
                    "should_not_exist": { "type": "boolean", "default": false }
                }
            },
            {
                "type": "object",
                "required": ["type", "command", "expected"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "exit_code" },
                    "command": { "type": "string" },
                    "expected": { "type": "integer" }
                }
            },
            {
                "type": "object",
                "description": "Use the agent's LLM to evaluate a natural language condition.",
                "required": ["type", "prompt"],
                "additionalProperties": false,
                "properties": {
                    "type": { "const": "llm_judge" },
                    "prompt": { "type": "string", "description": "Natural language condition to evaluate." }
                }
            }
        ]
    })
}

/// Write the schema to a file path, returning the schema JSON for display.
pub fn write_schema(output: &std::path::Path) -> Result<(), crate::error::AppError> {
    let schema = generate_task_schema();
    let pretty = serde_json::to_string_pretty(&schema)
        .map_err(|e| crate::error::AppError::Config(format!("Failed to serialize schema: {e}")))?;
    std::fs::write(output, format!("{pretty}\n")).map_err(|e| {
        crate::error::AppError::Config(format!("Failed to write {}: {e}", output.display()))
    })?;
    Ok(())
}
