use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::AppError;

const SUPPORTED_SCHEMA_VERSION: &str = "1.0";

/// Definition for a secret sourced from an environment variable.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SecretDef {
    /// Environment variable name to read the secret value from.
    pub env: String,
    /// Optional default value when the environment variable is not set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

/// A structured task definition for desktop app testing.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct TaskDefinition {
    /// Schema version (must be "1.0").
    pub schema_version: String,

    /// Unique identifier for the task.
    pub id: String,

    /// Natural language instruction for the agent.
    pub instruction: String,

    /// Optional completion condition — when the agent should consider the task done.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completion_condition: Option<String>,

    /// Application to test.
    pub app: AppConfig,

    /// Setup steps to run before the agent loop.
    #[serde(default)]
    pub config: Vec<SetupStep>,

    /// Evaluation configuration.
    #[serde(default)]
    pub evaluator: Option<EvaluatorConfig>,

    /// Overall test timeout in seconds.
    #[serde(default = "default_timeout")]
    pub timeout: u64,

    /// Maximum steps for the agent loop.
    #[serde(default = "default_max_steps")]
    pub max_steps: u32,

    /// Optional explicit a11y extraction timeout in seconds. Skips probe if set.
    #[serde(default)]
    pub a11y_timeout_secs: Option<u64>,

    /// Optional max a11y tree nodes to extract (default: 10000).
    #[serde(default)]
    pub max_a11y_nodes: Option<usize>,

    /// Named secrets sourced from environment variables.
    /// Keys are placeholder names used in `{{key}}` substitution.
    #[serde(default)]
    pub secrets: HashMap<String, SecretDef>,

    /// Optional metadata (tags, author, etc.).
    #[serde(default)]
    pub metadata: serde_json::Value,

    /// Path to a codified replay script (generated by `desktest codify`).
    /// Used with `desktest run --replay` for deterministic execution without an LLM.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replay_script: Option<String>,

    /// Path to directory containing expected screenshots for replay visual assertions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replay_screenshots_dir: Option<String>,

    /// Optional early exit condition — exit the agent loop early when met (with passed=false).
    /// The normal evaluator still runs afterward to determine the final verdict.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub early_exit: Option<EarlyExitConfig>,

    /// Internal flag: set by `apply_replay_override()` to indicate this task is
    /// in deterministic replay mode (no agent loop, just programmatic evaluation).
    /// Not serialized — this is runtime-only state.
    #[serde(skip)]
    pub(crate) replay_mode: bool,
}

fn default_timeout() -> u64 {
    300
}

fn default_max_steps() -> u32 {
    15
}

/// Application configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AppConfig {
    /// Deploy an AppImage file into the container.
    Appimage {
        path: String,
        #[serde(default)]
        electron: bool,
    },
    /// Deploy a folder-based app into the container.
    Folder {
        dir: String,
        entrypoint: String,
        #[serde(default)]
        electron: bool,
    },
    /// Use a pre-built custom Docker image.
    DockerImage {
        image: String,
        #[serde(default)]
        entrypoint_cmd: Option<String>,
        /// When true, the container gets `CAP_SYS_ADMIN` and `/dev/fuse`.
        /// Required for custom images that need FUSE (e.g. for mounting filesystems).
        #[serde(default)]
        needs_fuse: bool,
    },
    /// Attach to an existing running desktop (used with `desktest attach`).
    /// The app section is ignored in attach mode; this variant exists so
    /// task JSON files can signal they are designed for attach mode.
    VncAttach {
        #[serde(default)]
        note: Option<String>,
    },
    /// Run a macOS app inside a Tart VM (Apple Virtualization.framework).
    ///
    /// At least one of `bundle_id`, `app_path`, or `launch_cmd` must be provided.
    /// If `launch_cmd` is set it takes precedence; otherwise `open -b <bundle_id>`
    /// or `open <app_path>` is used.
    MacosTart {
        /// Tart base image to clone (e.g., "desktest-macos:latest").
        base_image: String,
        /// macOS bundle identifier (e.g., "com.apple.TextEdit"). Used with `open -b`.
        #[serde(default)]
        bundle_id: Option<String>,
        /// Path to a .app bundle inside the VM or on the host for deployment.
        #[serde(default)]
        app_path: Option<String>,
        /// Arbitrary launch command (takes precedence over bundle_id / app_path).
        #[serde(default)]
        launch_cmd: Option<String>,
        /// Whether this is an Electron app (adds accessibility flags).
        #[serde(default)]
        electron: bool,
    },
    /// Test a macOS app on the host desktop (no VM, no isolation).
    ///
    /// At least one of `bundle_id` or `app_path` must be provided.
    MacosNative {
        /// macOS bundle identifier (e.g., "com.apple.TextEdit").
        #[serde(default)]
        bundle_id: Option<String>,
        /// Path to a .app bundle on the host.
        #[serde(default)]
        app_path: Option<String>,
    },
    /// Run a Windows app inside a QEMU/KVM VM.
    ///
    /// At least one of `app_path` or `launch_cmd` must be provided.
    WindowsVm {
        /// Path to the QCOW2 golden image base.
        base_image: String,
        /// Path to an application file on the host for deployment into the VM.
        #[serde(default)]
        app_path: Option<String>,
        /// Arbitrary launch command (PowerShell). Takes precedence over app_path.
        #[serde(default)]
        launch_cmd: Option<String>,
        /// Installer command to run after deployment (e.g., msiexec).
        #[serde(default)]
        installer_cmd: Option<String>,
    },
    /// Test a Windows app on the host desktop (no VM, no isolation).
    ///
    /// Requires desktest compiled for Windows. At least one of `app_path` or
    /// `launch_cmd` must be provided.
    WindowsNative {
        /// Path to the application executable on the host.
        #[serde(default)]
        app_path: Option<String>,
        /// Arbitrary launch command (PowerShell/cmd). Takes precedence over app_path.
        #[serde(default)]
        launch_cmd: Option<String>,
    },
}

/// A setup step to execute before the agent loop.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SetupStep {
    /// Run a shell command inside the container.
    Execute { command: String },
    /// Copy a file or directory into the container.
    Copy { src: String, dest: String },
    /// Open a file with xdg-open or a specified application.
    Open {
        target: String,
        #[serde(default)]
        app: Option<String>,
    },
    /// Wait for a specified number of seconds.
    Sleep { seconds: f64 },
}

/// Evaluation configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EvaluatorConfig {
    /// Evaluation mode.
    pub mode: EvaluatorMode,

    /// Programmatic metrics to evaluate (used in programmatic and hybrid modes).
    #[serde(default)]
    pub metrics: Vec<MetricConfig>,

    /// How to combine multiple metrics: "and" (all must pass) or "or" (any must pass).
    #[serde(default = "default_conjunction")]
    pub conjunction: Conjunction,

    /// Per-execution timeout in seconds for evaluator commands (default: 120).
    #[serde(default)]
    pub eval_timeout_secs: Option<u64>,
}

fn default_conjunction() -> Conjunction {
    Conjunction::And
}

/// Evaluation mode.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EvaluatorMode {
    /// Only agent verdict (existing desktest behavior).
    Llm,
    /// Setup steps only + programmatic metrics (no agent loop).
    Programmatic,
    /// Agent verdict AND programmatic metrics both required.
    Hybrid,
}

/// How to combine multiple metric results.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Conjunction {
    And,
    Or,
}

/// A programmatic evaluation metric.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MetricConfig {
    /// Compare a file from the container against an expected file.
    FileCompare {
        /// Path to the file inside the container.
        actual_path: String,
        /// Path to the expected file on the host.
        expected_path: String,
        /// Comparison mode: "exact" or "normalized" (ignore trailing whitespace/newlines).
        #[serde(default = "default_compare_mode")]
        compare_mode: CompareMode,
    },
    /// Semantically compare structured data files (JSON, YAML, XML, CSV).
    FileCompareSemantic {
        /// Path to the file inside the container.
        actual_path: String,
        /// Path to the expected file on the host.
        expected_path: String,
        /// File format for parsing.
        format: SemanticFormat,
    },
    /// Run a command and check stdout.
    CommandOutput {
        /// Command to run inside the container.
        command: String,
        /// Expected output.
        expected: String,
        /// Match mode.
        #[serde(default = "default_match_mode")]
        match_mode: MatchMode,
    },
    /// Check if a file exists (or does not exist) in the container.
    FileExists {
        /// Path to check inside the container.
        path: String,
        /// If true, assert the file does NOT exist.
        #[serde(default)]
        should_not_exist: bool,
    },
    /// Run a command and check its exit code.
    ExitCode {
        /// Command to run inside the container.
        command: String,
        /// Expected exit code.
        expected: i32,
    },
    /// Run a Python replay script inside the container.
    ScriptReplay {
        /// Path to the Python script on the host.
        script_path: String,
        /// Optional directory containing expected screenshots (copied into container).
        #[serde(default)]
        screenshots_dir: Option<String>,
    },
}

fn default_compare_mode() -> CompareMode {
    CompareMode::Exact
}

fn default_match_mode() -> MatchMode {
    MatchMode::Contains
}

/// File comparison mode.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CompareMode {
    Exact,
    Normalized,
}

/// Supported formats for semantic file comparison.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SemanticFormat {
    Json,
    Yaml,
    Xml,
    Csv,
}

/// How to match command output.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MatchMode {
    Contains,
    Equals,
    Regex,
}

/// Condition for early exit — either a programmatic check or an LLM judgment.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EarlyExitCondition {
    /// Compare a file from the container against an expected file.
    FileCompare {
        actual_path: String,
        expected_path: String,
        #[serde(default = "default_compare_mode")]
        compare_mode: CompareMode,
    },
    /// Run a command and check stdout.
    CommandOutput {
        command: String,
        expected: String,
        #[serde(default = "default_match_mode")]
        match_mode: MatchMode,
    },
    /// Check if a file exists (or does not exist) in the container.
    FileExists {
        path: String,
        #[serde(default)]
        should_not_exist: bool,
    },
    /// Run a command and check its exit code.
    ExitCode { command: String, expected: i32 },
    /// Use the agent's LLM to evaluate a natural language condition against the
    /// current screenshot and accessibility tree.
    LlmJudge { prompt: String },
}

impl EarlyExitCondition {
    /// Convert programmatic variants to a `MetricConfig` for evaluation.
    /// Returns `None` for `LlmJudge` (handled separately).
    pub fn to_metric_config(&self) -> Option<MetricConfig> {
        match self {
            Self::FileCompare {
                actual_path,
                expected_path,
                compare_mode,
            } => Some(MetricConfig::FileCompare {
                actual_path: actual_path.clone(),
                expected_path: expected_path.clone(),
                compare_mode: compare_mode.clone(),
            }),
            Self::CommandOutput {
                command,
                expected,
                match_mode,
            } => Some(MetricConfig::CommandOutput {
                command: command.clone(),
                expected: expected.clone(),
                match_mode: match_mode.clone(),
            }),
            Self::FileExists {
                path,
                should_not_exist,
            } => Some(MetricConfig::FileExists {
                path: path.clone(),
                should_not_exist: *should_not_exist,
            }),
            Self::ExitCode { command, expected } => Some(MetricConfig::ExitCode {
                command: command.clone(),
                expected: *expected,
            }),
            Self::LlmJudge { .. } => None,
        }
    }
}

/// Early exit configuration — exit the agent loop early when a condition is met.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EarlyExitConfig {
    /// The condition to check each interval.
    pub condition: EarlyExitCondition,
    /// Check every N steps (default: 1).
    #[serde(default = "default_check_every")]
    pub check_every: u32,
    /// Optional human-readable message for the early exit reason.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

fn default_check_every() -> u32 {
    1
}

/// Replace `{{key}}` placeholders in `text` with values from `resolved`.
///
/// Any `{{key}}` that is not present in the `secrets` definition map produces an error.
fn substitute_secrets(
    text: &str,
    resolved: &HashMap<String, String>,
    defined: &HashMap<String, SecretDef>,
) -> Result<String, AppError> {
    let mut result = text.to_string();
    // Find all {{key}} placeholders
    let mut start = 0;
    while let Some(open) = result[start..].find("{{") {
        let open = start + open;
        if let Some(close) = result[open..].find("}}") {
            let close = open + close;
            let key = &result[open + 2..close];
            if !defined.contains_key(key) {
                return Err(AppError::Config(format!(
                    "Placeholder '{{{{{key}}}}}' references undefined secret '{key}'"
                )));
            }
            if let Some(value) = resolved.get(key) {
                result.replace_range(open..close + 2, value);
                start = open + value.len();
            } else {
                start = close + 2;
            }
        } else {
            break;
        }
    }
    Ok(result)
}

fn apply_secrets_to_metric(
    metric: &mut MetricConfig,
    resolved: &HashMap<String, String>,
    defined: &HashMap<String, SecretDef>,
) -> Result<(), AppError> {
    match metric {
        MetricConfig::FileCompare {
            actual_path,
            expected_path,
            ..
        }
        | MetricConfig::FileCompareSemantic {
            actual_path,
            expected_path,
            ..
        } => {
            *actual_path = substitute_secrets(actual_path, resolved, defined)?;
            *expected_path = substitute_secrets(expected_path, resolved, defined)?;
        }
        MetricConfig::CommandOutput {
            command, expected, ..
        } => {
            *command = substitute_secrets(command, resolved, defined)?;
            *expected = substitute_secrets(expected, resolved, defined)?;
        }
        MetricConfig::FileExists { path, .. } => {
            *path = substitute_secrets(path, resolved, defined)?;
        }
        MetricConfig::ExitCode { command, .. } => {
            *command = substitute_secrets(command, resolved, defined)?;
        }
        MetricConfig::ScriptReplay {
            script_path,
            screenshots_dir,
        } => {
            *script_path = substitute_secrets(script_path, resolved, defined)?;
            if let Some(dir) = screenshots_dir {
                *dir = substitute_secrets(dir, resolved, defined)?;
            }
        }
    }

    Ok(())
}

fn apply_secrets_to_early_exit(
    early_exit: &mut EarlyExitConfig,
    resolved: &HashMap<String, String>,
    defined: &HashMap<String, SecretDef>,
) -> Result<(), AppError> {
    match &mut early_exit.condition {
        EarlyExitCondition::FileCompare {
            actual_path,
            expected_path,
            ..
        } => {
            *actual_path = substitute_secrets(actual_path, resolved, defined)?;
            *expected_path = substitute_secrets(expected_path, resolved, defined)?;
        }
        EarlyExitCondition::CommandOutput {
            command, expected, ..
        } => {
            *command = substitute_secrets(command, resolved, defined)?;
            *expected = substitute_secrets(expected, resolved, defined)?;
        }
        EarlyExitCondition::FileExists { path, .. } => {
            *path = substitute_secrets(path, resolved, defined)?;
        }
        EarlyExitCondition::ExitCode { command, .. } => {
            *command = substitute_secrets(command, resolved, defined)?;
        }
        EarlyExitCondition::LlmJudge { prompt } => {
            *prompt = substitute_secrets(prompt, resolved, defined)?;
        }
    }
    Ok(())
}

fn apply_secrets_to_app(
    app: &mut AppConfig,
    resolved: &HashMap<String, String>,
    defined: &HashMap<String, SecretDef>,
) -> Result<(), AppError> {
    match app {
        AppConfig::Appimage { path, .. } => {
            *path = substitute_secrets(path, resolved, defined)?;
        }
        AppConfig::Folder {
            dir, entrypoint, ..
        } => {
            *dir = substitute_secrets(dir, resolved, defined)?;
            *entrypoint = substitute_secrets(entrypoint, resolved, defined)?;
        }
        AppConfig::DockerImage {
            image,
            entrypoint_cmd,
            ..
        } => {
            *image = substitute_secrets(image, resolved, defined)?;
            if let Some(cmd) = entrypoint_cmd {
                *cmd = substitute_secrets(cmd, resolved, defined)?;
            }
        }
        AppConfig::VncAttach { note } => {
            if let Some(text) = note {
                *text = substitute_secrets(text, resolved, defined)?;
            }
        }
        AppConfig::MacosTart {
            base_image,
            bundle_id,
            app_path,
            launch_cmd,
            ..
        } => {
            *base_image = substitute_secrets(base_image, resolved, defined)?;
            if let Some(bid) = bundle_id {
                *bid = substitute_secrets(bid, resolved, defined)?;
            }
            if let Some(ap) = app_path {
                *ap = substitute_secrets(ap, resolved, defined)?;
            }
            if let Some(cmd) = launch_cmd {
                *cmd = substitute_secrets(cmd, resolved, defined)?;
            }
        }
        AppConfig::MacosNative {
            bundle_id,
            app_path,
        } => {
            if let Some(bid) = bundle_id {
                *bid = substitute_secrets(bid, resolved, defined)?;
            }
            if let Some(ap) = app_path {
                *ap = substitute_secrets(ap, resolved, defined)?;
            }
        }
        AppConfig::WindowsVm {
            base_image,
            app_path,
            launch_cmd,
            installer_cmd,
        } => {
            *base_image = substitute_secrets(base_image, resolved, defined)?;
            if let Some(ap) = app_path {
                *ap = substitute_secrets(ap, resolved, defined)?;
            }
            if let Some(cmd) = launch_cmd {
                *cmd = substitute_secrets(cmd, resolved, defined)?;
            }
            if let Some(cmd) = installer_cmd {
                *cmd = substitute_secrets(cmd, resolved, defined)?;
            }
        }
        AppConfig::WindowsNative {
            app_path,
            launch_cmd,
        } => {
            if let Some(ap) = app_path {
                *ap = substitute_secrets(ap, resolved, defined)?;
            }
            if let Some(cmd) = launch_cmd {
                *cmd = substitute_secrets(cmd, resolved, defined)?;
            }
        }
    }

    Ok(())
}

impl TaskDefinition {
    /// Returns `true` if the task JSON contains a `replay_script` field.
    pub fn has_replay_script(&self) -> bool {
        self.replay_script.is_some()
    }

    /// Switch this task to replay mode: inject a `script_replay` metric and set programmatic mode.
    ///
    /// Returns `Err` if `replay_script` is `None`.
    pub fn apply_replay_override(&mut self) -> Result<(), AppError> {
        let script_path = self.replay_script.clone().ok_or_else(|| {
            AppError::Config("--replay requires a 'replay_script' path in the task JSON".into())
        })?;

        self.replay_mode = true;

        let replay_metric = MetricConfig::ScriptReplay {
            script_path,
            screenshots_dir: self.replay_screenshots_dir.clone(),
        };

        match &mut self.evaluator {
            Some(evaluator) => {
                evaluator.mode = EvaluatorMode::Programmatic;
                // Remove any existing ScriptReplay metrics to avoid duplicates
                evaluator
                    .metrics
                    .retain(|m| !matches!(m, MetricConfig::ScriptReplay { .. }));
                evaluator.metrics.insert(0, replay_metric);
            }
            None => {
                self.evaluator = Some(EvaluatorConfig {
                    mode: EvaluatorMode::Programmatic,
                    metrics: vec![replay_metric],
                    conjunction: Conjunction::And,
                    eval_timeout_secs: None,
                });
            }
        }

        Ok(())
    }

    /// Resolve all secrets by reading environment variables and applying defaults.
    ///
    /// Returns a map of secret name → resolved value, or an error if a required
    /// env var is missing and no default is provided.
    pub fn resolve_secrets(&self) -> Result<HashMap<String, String>, AppError> {
        let mut resolved = HashMap::new();
        for (name, def) in &self.secrets {
            let value = match std::env::var(&def.env) {
                Ok(v) => v,
                Err(_) => match &def.default {
                    Some(d) => d.clone(),
                    None => {
                        return Err(AppError::Config(format!(
                            "Secret '{name}': environment variable '{}' is not set and no default provided",
                            def.env
                        )));
                    }
                },
            };
            resolved.insert(name.clone(), value);
        }
        Ok(resolved)
    }

    /// Substitute `{{key}}` placeholders in instruction, completion_condition,
    /// app configuration, setup steps, and evaluator metric fields with
    /// resolved secret values.
    ///
    /// When no secrets are defined, this is a no-op so literal `{{...}}` text
    /// remains backward compatible. Once a task defines secrets, any
    /// `{{key}}` placeholder encountered in the supported fields must refer to
    /// a declared secret name or this returns an error.
    pub fn apply_secrets(&mut self, resolved: &HashMap<String, String>) -> Result<(), AppError> {
        if self.secrets.is_empty() {
            return Ok(());
        }

        self.instruction = substitute_secrets(&self.instruction, resolved, &self.secrets)?;
        if let Some(ref cond) = self.completion_condition {
            self.completion_condition = Some(substitute_secrets(cond, resolved, &self.secrets)?);
        }
        apply_secrets_to_app(&mut self.app, resolved, &self.secrets)?;
        for step in &mut self.config {
            match step {
                SetupStep::Execute { command } => {
                    *command = substitute_secrets(command, resolved, &self.secrets)?;
                }
                SetupStep::Copy { src, dest } => {
                    *src = substitute_secrets(src, resolved, &self.secrets)?;
                    *dest = substitute_secrets(dest, resolved, &self.secrets)?;
                }
                SetupStep::Open { target, app } => {
                    *target = substitute_secrets(target, resolved, &self.secrets)?;
                    if let Some(app) = app {
                        *app = substitute_secrets(app, resolved, &self.secrets)?;
                    }
                }
                SetupStep::Sleep { .. } => {}
            }
        }
        if let Some(evaluator) = &mut self.evaluator {
            for metric in &mut evaluator.metrics {
                apply_secrets_to_metric(metric, resolved, &self.secrets)?;
            }
        }
        if let Some(early_exit) = &mut self.early_exit {
            apply_secrets_to_early_exit(early_exit, resolved, &self.secrets)?;
        }
        Ok(())
    }

    /// Returns true if this task needs no LLM agent loop at all.
    ///
    /// Only true in replay mode — the agent loop is skipped entirely and only
    /// programmatic evaluation runs. Non-replay tasks with a `Programmatic`
    /// evaluator still run the agent loop; the evaluator mode only controls
    /// how success is measured.
    pub fn is_programmatic_only(&self) -> bool {
        self.replay_mode
            && self
                .evaluator
                .as_ref()
                .is_some_and(|e| matches!(e.mode, EvaluatorMode::Programmatic))
    }

    /// Build the full instruction string, appending the completion condition if present.
    pub fn full_instruction(&self) -> String {
        match &self.completion_condition {
            Some(cond) => format!("{}\n\nCompletion Condition: {}", self.instruction, cond),
            None => self.instruction.clone(),
        }
    }

    /// Load and validate a task definition from a JSON file.
    pub fn load(path: &Path) -> Result<Self, AppError> {
        let contents = std::fs::read_to_string(path).map_err(|e| {
            AppError::Config(format!("Cannot read task file '{}': {e}", path.display()))
        })?;

        let mut task = Self::parse_and_validate(&contents)?;

        // Resolve relative replay_script / replay_screenshots_dir paths
        // relative to the task JSON file's parent directory.
        // Canonicalize task_dir so resolved paths are absolute even when
        // the task file path itself is relative (e.g. ../other-dir/task.json).
        if let Some(task_dir) = path.parent() {
            let task_dir =
                std::fs::canonicalize(task_dir).unwrap_or_else(|_| task_dir.to_path_buf());
            if let Some(ref script) = task.replay_script {
                let p = Path::new(script);
                if p.is_relative() {
                    let resolved = task_dir.join(p);
                    task.replay_script = Some(resolved.to_string_lossy().into_owned());
                }
            }
            if let Some(ref dir) = task.replay_screenshots_dir {
                let p = Path::new(dir);
                if p.is_relative() {
                    let resolved = task_dir.join(p);
                    task.replay_screenshots_dir = Some(resolved.to_string_lossy().into_owned());
                }
            }
        }

        Ok(task)
    }

    /// Parse JSON string and validate the task definition.
    pub fn parse_and_validate(json: &str) -> Result<Self, AppError> {
        let task: TaskDefinition = serde_json::from_str(json)
            .map_err(|e| AppError::Config(format!("Invalid task JSON: {e}")))?;

        task.validate()?;
        Ok(task)
    }

    fn validate(&self) -> Result<(), AppError> {
        if self.schema_version != SUPPORTED_SCHEMA_VERSION {
            return Err(AppError::Config(format!(
                "Unsupported schema_version '{}'. Expected '{SUPPORTED_SCHEMA_VERSION}'.",
                self.schema_version
            )));
        }

        if self.id.is_empty() {
            return Err(AppError::Config("Task 'id' must not be empty.".into()));
        }

        if self.instruction.is_empty() {
            return Err(AppError::Config(
                "Task 'instruction' must not be empty.".into(),
            ));
        }

        if self.timeout == 0 {
            return Err(AppError::Config("Task 'timeout' must be > 0.".into()));
        }

        if self.max_steps == 0 {
            return Err(AppError::Config("Task 'max_steps' must be > 0.".into()));
        }

        if let Some(0) = self.a11y_timeout_secs {
            return Err(AppError::Config(
                "Task 'a11y_timeout_secs' must be > 0 if specified.".into(),
            ));
        }

        if let Some(0) = self.max_a11y_nodes {
            return Err(AppError::Config(
                "Task 'max_a11y_nodes' must be > 0 if specified.".into(),
            ));
        }

        validate_setup_steps(&self.config)?;

        if let Some(evaluator) = &self.evaluator {
            validate_evaluator(evaluator)?;
        }

        if let Some(early_exit) = &self.early_exit {
            validate_early_exit(early_exit)?;
        }

        validate_app_config(&self.app)?;

        Ok(())
    }
}

fn validate_setup_steps(steps: &[SetupStep]) -> Result<(), AppError> {
    for (i, step) in steps.iter().enumerate() {
        match step {
            SetupStep::Execute { command } if command.is_empty() => {
                return Err(AppError::Config(format!(
                    "Setup step {i}: 'execute' command must not be empty."
                )));
            }
            SetupStep::Copy { src, dest } => {
                if src.is_empty() {
                    return Err(AppError::Config(format!(
                        "Setup step {i}: 'copy' src must not be empty."
                    )));
                }
                if dest.is_empty() {
                    return Err(AppError::Config(format!(
                        "Setup step {i}: 'copy' dest must not be empty."
                    )));
                }
            }
            SetupStep::Open { target, .. } if target.is_empty() => {
                return Err(AppError::Config(format!(
                    "Setup step {i}: 'open' target must not be empty."
                )));
            }
            SetupStep::Sleep { seconds } if *seconds <= 0.0 => {
                return Err(AppError::Config(format!(
                    "Setup step {i}: 'sleep' seconds must be > 0."
                )));
            }
            _ => {}
        }
    }
    Ok(())
}

fn validate_evaluator(evaluator: &EvaluatorConfig) -> Result<(), AppError> {
    match evaluator.mode {
        EvaluatorMode::Programmatic | EvaluatorMode::Hybrid => {
            if evaluator.metrics.is_empty() {
                return Err(AppError::Config(format!(
                    "Evaluator mode '{}' requires at least one metric.",
                    if evaluator.mode == EvaluatorMode::Programmatic {
                        "programmatic"
                    } else {
                        "hybrid"
                    }
                )));
            }
        }
        EvaluatorMode::Llm => {}
    }

    if let Some(0) = evaluator.eval_timeout_secs {
        return Err(AppError::Config(
            "Evaluator 'eval_timeout_secs' must be > 0 if specified.".into(),
        ));
    }

    for (i, metric) in evaluator.metrics.iter().enumerate() {
        validate_metric(i, metric)?;
    }

    Ok(())
}

fn validate_metric(i: usize, metric: &MetricConfig) -> Result<(), AppError> {
    match metric {
        MetricConfig::FileCompare {
            actual_path,
            expected_path,
            ..
        } => {
            if actual_path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (file_compare): 'actual_path' must not be empty."
                )));
            }
            if expected_path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (file_compare): 'expected_path' must not be empty."
                )));
            }
        }
        MetricConfig::FileCompareSemantic {
            actual_path,
            expected_path,
            ..
        } => {
            if actual_path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (file_compare_semantic): 'actual_path' must not be empty."
                )));
            }
            if expected_path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (file_compare_semantic): 'expected_path' must not be empty."
                )));
            }
        }
        MetricConfig::CommandOutput {
            command, expected, ..
        } => {
            if command.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (command_output): 'command' must not be empty."
                )));
            }
            if expected.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (command_output): 'expected' must not be empty."
                )));
            }
        }
        MetricConfig::FileExists { path, .. } => {
            if path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (file_exists): 'path' must not be empty."
                )));
            }
        }
        MetricConfig::ExitCode { command, .. } => {
            if command.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (exit_code): 'command' must not be empty."
                )));
            }
        }
        MetricConfig::ScriptReplay { script_path, .. } => {
            if script_path.is_empty() {
                return Err(AppError::Config(format!(
                    "Metric {i} (script_replay): 'script_path' must not be empty."
                )));
            }
        }
    }
    Ok(())
}

fn validate_early_exit(early_exit: &EarlyExitConfig) -> Result<(), AppError> {
    if early_exit.check_every == 0 {
        return Err(AppError::Config(
            "Early exit 'check_every' must be > 0.".into(),
        ));
    }

    match &early_exit.condition {
        EarlyExitCondition::FileCompare {
            actual_path,
            expected_path,
            ..
        } => {
            if actual_path.is_empty() {
                return Err(AppError::Config(
                    "Early exit file_compare: 'actual_path' must not be empty.".into(),
                ));
            }
            if expected_path.is_empty() {
                return Err(AppError::Config(
                    "Early exit file_compare: 'expected_path' must not be empty.".into(),
                ));
            }
        }
        EarlyExitCondition::CommandOutput {
            command, expected, ..
        } => {
            if command.is_empty() {
                return Err(AppError::Config(
                    "Early exit command_output: 'command' must not be empty.".into(),
                ));
            }
            if expected.is_empty() {
                return Err(AppError::Config(
                    "Early exit command_output: 'expected' must not be empty.".into(),
                ));
            }
        }
        EarlyExitCondition::FileExists { path, .. } => {
            if path.is_empty() {
                return Err(AppError::Config(
                    "Early exit file_exists: 'path' must not be empty.".into(),
                ));
            }
        }
        EarlyExitCondition::ExitCode { command, .. } => {
            if command.is_empty() {
                return Err(AppError::Config(
                    "Early exit exit_code: 'command' must not be empty.".into(),
                ));
            }
        }
        EarlyExitCondition::LlmJudge { prompt } => {
            if prompt.is_empty() {
                return Err(AppError::Config(
                    "Early exit llm_judge: 'prompt' must not be empty.".into(),
                ));
            }
        }
    }
    Ok(())
}

fn validate_app_config(app: &AppConfig) -> Result<(), AppError> {
    match app {
        AppConfig::MacosTart {
            base_image,
            bundle_id,
            app_path,
            launch_cmd,
            ..
        } => {
            if base_image.is_empty() {
                return Err(AppError::Config(
                    "MacosTart app: 'base_image' must not be empty.".into(),
                ));
            }
            if bundle_id.is_none() && app_path.is_none() && launch_cmd.is_none() {
                return Err(AppError::Config(
                    "MacosTart app: at least one of 'bundle_id', 'app_path', or 'launch_cmd' must be specified.".into(),
                ));
            }
        }
        AppConfig::MacosNative {
            bundle_id,
            app_path,
        } => {
            if bundle_id.is_none() && app_path.is_none() {
                return Err(AppError::Config(
                    "MacosNative app: at least one of 'bundle_id' or 'app_path' must be specified."
                        .into(),
                ));
            }
        }
        _ => {}
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::sync::{Mutex, OnceLock};

    use super::*;

    fn env_lock() -> &'static Mutex<()> {
        static ENV_LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        ENV_LOCK.get_or_init(|| Mutex::new(()))
    }

    fn minimal_valid_task() -> &'static str {
        r#"{
            "schema_version": "1.0",
            "id": "test-001",
            "instruction": "Open gedit and type hello",
            "app": {
                "type": "appimage",
                "path": "/apps/gedit.AppImage"
            }
        }"#
    }

    #[test]
    fn test_parse_minimal_task() {
        let task = TaskDefinition::parse_and_validate(minimal_valid_task()).unwrap();
        assert_eq!(task.schema_version, "1.0");
        assert_eq!(task.id, "test-001");
        assert_eq!(task.instruction, "Open gedit and type hello");
        assert!(matches!(task.app, AppConfig::Appimage { .. }));
        assert!(task.config.is_empty());
        assert!(task.evaluator.is_none());
        assert_eq!(task.timeout, 300);
        assert_eq!(task.max_steps, 15);
    }

    #[test]
    fn test_parse_full_task() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "gedit-save-test",
            "instruction": "Open gedit, type 'hello world', save as /tmp/output.txt",
            "app": {
                "type": "folder",
                "dir": "/apps/gedit",
                "entrypoint": "gedit"
            },
            "config": [
                {"type": "execute", "command": "mkdir -p /tmp/test"},
                {"type": "copy", "src": "fixtures/input.txt", "dest": "/home/tester/input.txt"},
                {"type": "open", "target": "/home/tester/input.txt", "app": "gedit"},
                {"type": "sleep", "seconds": 2.0}
            ],
            "evaluator": {
                "mode": "hybrid",
                "metrics": [
                    {
                        "type": "file_compare",
                        "actual_path": "/tmp/output.txt",
                        "expected_path": "fixtures/expected.txt",
                        "compare_mode": "normalized"
                    },
                    {
                        "type": "command_output",
                        "command": "cat /tmp/output.txt",
                        "expected": "hello world",
                        "match_mode": "contains"
                    },
                    {
                        "type": "file_exists",
                        "path": "/tmp/output.txt"
                    },
                    {
                        "type": "exit_code",
                        "command": "test -f /tmp/output.txt",
                        "expected": 0
                    }
                ],
                "conjunction": "and"
            },
            "timeout": 120,
            "max_steps": 20,
            "metadata": {"author": "test", "tags": ["gedit", "save"]}
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert_eq!(task.id, "gedit-save-test");
        assert!(matches!(task.app, AppConfig::Folder { .. }));
        assert_eq!(task.config.len(), 4);
        let evaluator = task.evaluator.unwrap();
        assert_eq!(evaluator.mode, EvaluatorMode::Hybrid);
        assert_eq!(evaluator.metrics.len(), 4);
        assert_eq!(evaluator.conjunction, Conjunction::And);
        assert_eq!(task.timeout, 120);
        assert_eq!(task.max_steps, 20);
    }

    #[test]
    fn test_parse_docker_image_app() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "libreoffice-test",
            "instruction": "Open LibreOffice Writer",
            "app": {
                "type": "docker_image",
                "image": "my-libreoffice:latest",
                "entrypoint_cmd": "libreoffice --writer"
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        match &task.app {
            AppConfig::DockerImage {
                image,
                entrypoint_cmd,
                ..
            } => {
                assert_eq!(image, "my-libreoffice:latest");
                assert_eq!(entrypoint_cmd.as_deref(), Some("libreoffice --writer"));
            }
            _ => panic!("Expected DockerImage app config"),
        }
    }

    #[test]
    fn test_parse_semantic_compare_metric() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "json-compare-test",
            "instruction": "Edit JSON file",
            "app": {"type": "appimage", "path": "/apps/editor.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [{
                    "type": "file_compare_semantic",
                    "actual_path": "/tmp/output.json",
                    "expected_path": "fixtures/expected.json",
                    "format": "json"
                }]
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let evaluator = task.evaluator.unwrap();
        match &evaluator.metrics[0] {
            MetricConfig::FileCompareSemantic { format, .. } => {
                assert_eq!(*format, SemanticFormat::Json);
            }
            _ => panic!("Expected FileCompareSemantic metric"),
        }
    }

    #[test]
    fn test_reject_unsupported_schema_version() {
        let json = r#"{
            "schema_version": "2.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"}
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(matches!(err, AppError::Config(_)));
        assert!(err.to_string().contains("Unsupported schema_version"));
        assert!(err.to_string().contains("2.0"));
    }

    #[test]
    fn test_reject_empty_id() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"}
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("id"));
    }

    #[test]
    fn test_reject_empty_instruction() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"}
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("instruction"));
    }

    #[test]
    fn test_reject_missing_required_field() {
        // Missing schema_version
        let json = r#"{
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"}
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(matches!(err, AppError::Config(_)));
        assert!(err.to_string().contains("schema_version"));
    }

    #[test]
    fn test_reject_unknown_app_type() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "flatpak", "path": "/apps/test"}
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(matches!(err, AppError::Config(_)));
    }

    #[test]
    fn test_reject_invalid_json() {
        let err = TaskDefinition::parse_and_validate("not json").unwrap_err();
        assert!(matches!(err, AppError::Config(_)));
        assert!(err.to_string().contains("Invalid task JSON"));
    }

    #[test]
    fn test_reject_empty_execute_command() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "config": [{"type": "execute", "command": ""}]
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("execute"));
        assert!(err.to_string().contains("command"));
    }

    #[test]
    fn test_reject_empty_copy_src() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "config": [{"type": "copy", "src": "", "dest": "/tmp/file"}]
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("copy"));
        assert!(err.to_string().contains("src"));
    }

    #[test]
    fn test_reject_zero_sleep() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "config": [{"type": "sleep", "seconds": 0}]
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("sleep"));
        assert!(err.to_string().contains("seconds"));
    }

    #[test]
    fn test_reject_programmatic_mode_without_metrics() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": []
            }
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("programmatic"));
        assert!(err.to_string().contains("metric"));
    }

    #[test]
    fn test_reject_hybrid_mode_without_metrics() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "hybrid",
                "metrics": []
            }
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("hybrid"));
        assert!(err.to_string().contains("metric"));
    }

    #[test]
    fn test_llm_mode_without_metrics_is_ok() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "llm",
                "metrics": []
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert_eq!(task.evaluator.unwrap().mode, EvaluatorMode::Llm);
    }

    #[test]
    fn test_or_conjunction() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "conjunction": "or",
                "metrics": [
                    {"type": "file_exists", "path": "/tmp/a"},
                    {"type": "file_exists", "path": "/tmp/b"}
                ]
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let evaluator = task.evaluator.unwrap();
        assert_eq!(evaluator.conjunction, Conjunction::Or);
    }

    #[test]
    fn test_reject_empty_metric_path() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [{"type": "file_exists", "path": ""}]
            }
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("file_exists"));
        assert!(err.to_string().contains("path"));
    }

    #[test]
    fn test_defaults_for_timeout_and_max_steps() {
        let task = TaskDefinition::parse_and_validate(minimal_valid_task()).unwrap();
        assert_eq!(task.timeout, 300);
        assert_eq!(task.max_steps, 15);
    }

    #[test]
    fn test_match_mode_variants() {
        for (mode_str, expected) in [
            ("contains", MatchMode::Contains),
            ("equals", MatchMode::Equals),
            ("regex", MatchMode::Regex),
        ] {
            let json = format!(
                r#"{{
                    "schema_version": "1.0",
                    "id": "test",
                    "instruction": "test",
                    "app": {{"type": "appimage", "path": "/apps/test.AppImage"}},
                    "evaluator": {{
                        "mode": "programmatic",
                        "metrics": [{{
                            "type": "command_output",
                            "command": "echo hi",
                            "expected": "hi",
                            "match_mode": "{mode_str}"
                        }}]
                    }}
                }}"#
            );
            let task = TaskDefinition::parse_and_validate(&json).unwrap();
            let evaluator = task.evaluator.unwrap();
            match &evaluator.metrics[0] {
                MetricConfig::CommandOutput { match_mode, .. } => {
                    assert_eq!(*match_mode, expected);
                }
                _ => panic!("Expected CommandOutput"),
            }
        }
    }

    #[test]
    fn test_parse_electron_folder_app() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "electron-test",
            "instruction": "Open the Electron app",
            "app": {
                "type": "folder",
                "dir": "/apps/myelectronapp",
                "entrypoint": "myelectronapp",
                "electron": true
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        match &task.app {
            AppConfig::Folder {
                dir,
                entrypoint,
                electron,
            } => {
                assert_eq!(dir, "/apps/myelectronapp");
                assert_eq!(entrypoint, "myelectronapp");
                assert!(electron);
            }
            _ => panic!("Expected Folder app config"),
        }
    }

    #[test]
    fn test_parse_folder_app_electron_defaults_false() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "folder-test",
            "instruction": "Open the app",
            "app": {
                "type": "folder",
                "dir": "/apps/myapp",
                "entrypoint": "myapp"
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        match &task.app {
            AppConfig::Folder { electron, .. } => {
                assert!(!electron);
            }
            _ => panic!("Expected Folder app config"),
        }
    }

    #[test]
    fn test_load_nonexistent_file() {
        let err = TaskDefinition::load(Path::new("/nonexistent/task.json")).unwrap_err();
        assert!(matches!(err, AppError::Config(_)));
        assert!(err.to_string().contains("Cannot read task file"));
    }

    #[test]
    fn test_reject_zero_timeout() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "timeout": 0
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("timeout"));
    }

    #[test]
    fn test_reject_zero_max_steps() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "max_steps": 0
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("max_steps"));
    }

    #[test]
    fn test_reject_zero_a11y_timeout_secs() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "a11y_timeout_secs": 0
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("a11y_timeout_secs"));
    }

    #[test]
    fn test_reject_zero_max_a11y_nodes() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "max_a11y_nodes": 0
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("max_a11y_nodes"));
    }

    #[test]
    fn test_valid_a11y_overrides() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "a11y_timeout_secs": 30,
            "max_a11y_nodes": 5000
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert_eq!(task.a11y_timeout_secs, Some(30));
        assert_eq!(task.max_a11y_nodes, Some(5000));
    }

    #[test]
    fn test_regex_match_mode() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [{
                    "type": "command_output",
                    "command": "echo hello123",
                    "expected": "hello\\d+",
                    "match_mode": "regex"
                }]
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let evaluator = task.evaluator.unwrap();
        match &evaluator.metrics[0] {
            MetricConfig::CommandOutput { match_mode, .. } => {
                assert_eq!(*match_mode, MatchMode::Regex);
            }
            _ => panic!("Expected CommandOutput"),
        }
    }

    #[test]
    fn test_reject_zero_eval_timeout_secs() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [{"type": "file_exists", "path": "/tmp/a"}],
                "eval_timeout_secs": 0
            }
        }"#;

        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("eval_timeout_secs"));
    }

    #[test]
    fn test_valid_eval_timeout_secs() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "test",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [{"type": "file_exists", "path": "/tmp/a"}],
                "eval_timeout_secs": 60
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert_eq!(task.evaluator.unwrap().eval_timeout_secs, Some(60));
    }

    #[test]
    fn test_parse_vnc_attach_app() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "attach-test",
            "instruction": "Click the OK button",
            "app": {
                "type": "vnc_attach",
                "note": "This task is designed for desktest attach mode"
            }
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        match &task.app {
            AppConfig::VncAttach { note } => {
                assert_eq!(
                    note.as_deref(),
                    Some("This task is designed for desktest attach mode")
                );
            }
            _ => panic!("Expected VncAttach app config"),
        }
    }

    #[test]
    fn test_parse_vnc_attach_app_minimal() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "attach-test",
            "instruction": "Click the OK button",
            "app": {"type": "vnc_attach"}
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert!(matches!(task.app, AppConfig::VncAttach { .. }));
    }

    #[test]
    fn test_vnc_attach_with_evaluator() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "attach-eval-test",
            "instruction": "Approve the dialog",
            "app": {"type": "vnc_attach"},
            "evaluator": {"mode": "llm"},
            "timeout": 60,
            "max_steps": 10
        }"#;

        let task = TaskDefinition::parse_and_validate(json).unwrap();
        assert!(matches!(task.app, AppConfig::VncAttach { .. }));
        assert_eq!(task.timeout, 60);
        assert_eq!(task.max_steps, 10);
        assert_eq!(task.evaluator.unwrap().mode, EvaluatorMode::Llm);
    }

    #[test]
    fn test_secrets_resolve_from_env() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Log in as {{username}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "secrets": {
                "username": {"env": "DESKTEST_TEST_USERNAME"}
            }
        }"#;

        unsafe { std::env::set_var("DESKTEST_TEST_USERNAME", "alice") };
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        assert_eq!(resolved["username"], "alice");
        unsafe { std::env::remove_var("DESKTEST_TEST_USERNAME") };
    }

    #[test]
    fn test_secrets_default_value() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Log in as {{username}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "secrets": {
                "username": {"env": "DESKTEST_TEST_NOEXIST_VAR", "default": "testuser"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_NOEXIST_VAR") };
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        assert_eq!(resolved["username"], "testuser");
    }

    #[test]
    fn test_secrets_missing_env_no_default() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Log in as {{password}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "secrets": {
                "password": {"env": "DESKTEST_TEST_NOEXIST_PASS"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_NOEXIST_PASS") };
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let err = task.resolve_secrets().unwrap_err();
        assert!(err.to_string().contains("DESKTEST_TEST_NOEXIST_PASS"));
        assert!(err.to_string().contains("not set"));
    }

    #[test]
    fn test_secrets_apply_substitution() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Log in as {{username}} with {{password}}",
            "completion_condition": "See {{username}} in the header",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "config": [
                {"type": "execute", "command": "echo '{{password}}' > /tmp/.token"}
            ],
            "secrets": {
                "username": {"env": "DESKTEST_TEST_U", "default": "alice"},
                "password": {"env": "DESKTEST_TEST_P", "default": "s3cret"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_U") };
        unsafe { std::env::remove_var("DESKTEST_TEST_P") };
        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        task.apply_secrets(&resolved).unwrap();

        assert_eq!(task.instruction, "Log in as alice with s3cret");
        assert_eq!(
            task.completion_condition.as_deref(),
            Some("See alice in the header")
        );
        match &task.config[0] {
            SetupStep::Execute { command } => {
                assert_eq!(command, "echo 's3cret' > /tmp/.token");
            }
            _ => panic!("Expected Execute step"),
        }
    }

    #[test]
    fn test_secrets_apply_substitution_in_copy_and_open_steps() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Use {{username}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "config": [
                {"type": "copy", "src": "/home/{{username}}/data.txt", "dest": "/tmp/{{username}}/"},
                {"type": "open", "target": "/tmp/{{username}}/report.txt", "app": "{{viewer}}"}
            ],
            "secrets": {
                "username": {"env": "DESKTEST_TEST_COPY_USER", "default": "alice"},
                "viewer": {"env": "DESKTEST_TEST_OPEN_APP", "default": "xdg-open"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_COPY_USER") };
        unsafe { std::env::remove_var("DESKTEST_TEST_OPEN_APP") };
        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        task.apply_secrets(&resolved).unwrap();

        match &task.config[0] {
            SetupStep::Copy { src, dest } => {
                assert_eq!(src, "/home/alice/data.txt");
                assert_eq!(dest, "/tmp/alice/");
            }
            _ => panic!("Expected Copy step"),
        }
        match &task.config[1] {
            SetupStep::Open { target, app } => {
                assert_eq!(target, "/tmp/alice/report.txt");
                assert_eq!(app.as_deref(), Some("xdg-open"));
            }
            _ => panic!("Expected Open step"),
        }
    }

    #[test]
    fn test_secrets_undefined_placeholder() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Log in with {{undefined_key}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "secrets": {
                "defined_key": {"env": "DESKTEST_DEFINED_KEY", "default": "value"}
            }
        }"#;

        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        let err = task.apply_secrets(&resolved).unwrap_err();
        assert!(err.to_string().contains("undefined_key"));
    }

    #[test]
    fn test_secrets_apply_substitution_in_evaluator_metrics() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Check {{username}}",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "evaluator": {
                "mode": "programmatic",
                "metrics": [
                    {
                        "type": "command_output",
                        "command": "echo {{username}}",
                        "expected": "{{username}}",
                        "match_mode": "contains"
                    },
                    {
                        "type": "file_exists",
                        "path": "/tmp/{{username}}.txt"
                    }
                ]
            },
            "secrets": {
                "username": {"env": "DESKTEST_TEST_EVAL_USER", "default": "alice"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_EVAL_USER") };
        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        task.apply_secrets(&resolved).unwrap();

        let evaluator = task.evaluator.expect("evaluator");
        match &evaluator.metrics[0] {
            MetricConfig::CommandOutput {
                command, expected, ..
            } => {
                assert_eq!(command, "echo alice");
                assert_eq!(expected, "alice");
            }
            _ => panic!("Expected CommandOutput metric"),
        }
        match &evaluator.metrics[1] {
            MetricConfig::FileExists { path, .. } => {
                assert_eq!(path, "/tmp/alice.txt");
            }
            _ => panic!("Expected FileExists metric"),
        }
    }

    #[test]
    fn test_secrets_apply_substitution_in_app_config() {
        let _guard = env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Run app",
            "app": {
                "type": "docker_image",
                "image": "{{registry}}/myapp:{{tag}}",
                "entrypoint_cmd": "run --token {{token}}"
            },
            "secrets": {
                "registry": {"env": "DESKTEST_TEST_REGISTRY", "default": "registry.local"},
                "tag": {"env": "DESKTEST_TEST_TAG", "default": "stable"},
                "token": {"env": "DESKTEST_TEST_TOKEN", "default": "abc123"}
            }
        }"#;

        unsafe { std::env::remove_var("DESKTEST_TEST_REGISTRY") };
        unsafe { std::env::remove_var("DESKTEST_TEST_TAG") };
        unsafe { std::env::remove_var("DESKTEST_TEST_TOKEN") };
        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        task.apply_secrets(&resolved).unwrap();

        match &task.app {
            AppConfig::DockerImage {
                image,
                entrypoint_cmd,
                ..
            } => {
                assert_eq!(image, "registry.local/myapp:stable");
                assert_eq!(entrypoint_cmd.as_deref(), Some("run --token abc123"));
            }
            _ => panic!("Expected DockerImage app"),
        }
    }

    #[test]
    fn test_secrets_empty_map_backward_compat() {
        let mut task = TaskDefinition::parse_and_validate(minimal_valid_task()).unwrap();
        assert!(task.secrets.is_empty());
        let resolved = task.resolve_secrets().unwrap();
        assert!(resolved.is_empty());
        task.apply_secrets(&resolved).unwrap();
        assert_eq!(task.instruction, "Open gedit and type hello");
    }

    #[test]
    fn test_literal_braces_without_secrets_remain_unchanged() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test",
            "instruction": "Render {{name}} literally",
            "completion_condition": "Expect {{status}} text",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"}
        }"#;

        let mut task = TaskDefinition::parse_and_validate(json).unwrap();
        let resolved = task.resolve_secrets().unwrap();
        task.apply_secrets(&resolved).unwrap();

        assert_eq!(task.instruction, "Render {{name}} literally");
        assert_eq!(
            task.completion_condition.as_deref(),
            Some("Expect {{status}} text")
        );
    }

    // --- Early exit tests ---

    #[test]
    fn test_early_exit_command_output_parses() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test-early-exit",
            "instruction": "Do something",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "early_exit": {
                "condition": {
                    "type": "command_output",
                    "command": "pgrep myapp || echo CRASHED",
                    "expected": "CRASHED",
                    "match_mode": "contains"
                },
                "check_every": 2,
                "message": "App crashed"
            }
        }"#;
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let early_exit = task.early_exit.unwrap();
        assert_eq!(early_exit.check_every, 2);
        assert_eq!(early_exit.message.as_deref(), Some("App crashed"));
        assert!(matches!(
            early_exit.condition,
            EarlyExitCondition::CommandOutput { .. }
        ));
    }

    #[test]
    fn test_early_exit_llm_judge_parses() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test-early-exit-llm",
            "instruction": "Do something",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "early_exit": {
                "condition": {
                    "type": "llm_judge",
                    "prompt": "Is there a fatal error dialog visible?"
                },
                "check_every": 3
            }
        }"#;
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let early_exit = task.early_exit.unwrap();
        assert_eq!(early_exit.check_every, 3);
        assert!(early_exit.message.is_none());
        assert!(matches!(
            early_exit.condition,
            EarlyExitCondition::LlmJudge { .. }
        ));
    }

    #[test]
    fn test_early_exit_file_exists_parses() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test-early-exit-file",
            "instruction": "Do something",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "early_exit": {
                "condition": {
                    "type": "file_exists",
                    "path": "/tmp/crash.log"
                }
            }
        }"#;
        let task = TaskDefinition::parse_and_validate(json).unwrap();
        let early_exit = task.early_exit.unwrap();
        assert_eq!(early_exit.check_every, 1); // default
        assert!(matches!(
            early_exit.condition,
            EarlyExitCondition::FileExists { .. }
        ));
    }

    #[test]
    fn test_early_exit_check_every_zero_rejected() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test-bad",
            "instruction": "Do something",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "early_exit": {
                "condition": {"type": "file_exists", "path": "/tmp/x"},
                "check_every": 0
            }
        }"#;
        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("check_every"));
    }

    #[test]
    fn test_early_exit_empty_prompt_rejected() {
        let json = r#"{
            "schema_version": "1.0",
            "id": "test-bad",
            "instruction": "Do something",
            "app": {"type": "appimage", "path": "/apps/test.AppImage"},
            "early_exit": {
                "condition": {"type": "llm_judge", "prompt": ""}
            }
        }"#;
        let err = TaskDefinition::parse_and_validate(json).unwrap_err();
        assert!(err.to_string().contains("prompt"));
    }

    #[test]
    fn test_early_exit_to_metric_config() {
        let condition = EarlyExitCondition::CommandOutput {
            command: "echo hi".into(),
            expected: "hi".into(),
            match_mode: MatchMode::Contains,
        };
        let metric = condition.to_metric_config().unwrap();
        assert!(matches!(metric, MetricConfig::CommandOutput { .. }));

        let llm = EarlyExitCondition::LlmJudge {
            prompt: "test".into(),
        };
        assert!(llm.to_metric_config().is_none());
    }

    #[test]
    fn test_early_exit_not_required() {
        let task = TaskDefinition::parse_and_validate(minimal_valid_task()).unwrap();
        assert!(task.early_exit.is_none());
    }
}
